# Generated by Django 4.0.5 on 2022-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('author', models.TextField()),
                ('time', models.DateTimeField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
