# Generated by Django 4.0.5 on 2022-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPost', '0002_rename_product_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.TextField(default='No author'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
