# Generated by Django 4.0.5 on 2022-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPost', '0004_alter_newspost_author_alter_newspost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
