# Generated by Django 4.0.5 on 2022-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPost', '0005_newspost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='domain',
            field=models.CharField(default='facebook.com', max_length=300),
            preserve_default=False,
        ),
    ]
