# Generated by Django 4.0.5 on 2022-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
