# Generated by Django 3.2.13 on 2022-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_comment_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
